/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isai.gym.submenus;

import com.isai.gym.clases.Huella;
import com.isai.gym.clases.Utilerias;
import com.isai.gym.paneles.Clientes;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author isai_
 */
public class SubHuella extends javax.swing.JDialog {
    
    Huella huella;
    Utilerias util=new Utilerias();
    int idCliente=0;
    String nombreCliente="";
    private String identificadorHuella="";

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form Huella
     */
    public SubHuella() {
        
        initComponents();
        btngroupMano.add(rbtnIzquierda);
        btngroupMano.add(rbtnDerecha);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btngroupMano = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        panelHuella = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblMsg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        rbtnIzquierda = new javax.swing.JRadioButton();
        rbtnDerecha = new javax.swing.JRadioButton();
        cmbDedo = new javax.swing.JComboBox<>();
        lblImagen = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(Color.decode(util.colorFondo)
        );
        jPanel1.setMinimumSize(new java.awt.Dimension(222, 250));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setBackground(Color.decode(util.colorPrimario)
        );
        okButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_32/ic_disquete.png"))); // NOI18N
        okButton.setText("Guardar");
        okButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        okButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);
        getRootPane().setDefaultButton(okButton);

        cancelButton.setBackground(Color.decode(util.colorPrimario)
        );
        cancelButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_32/ic_cancelar.png"))); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panelHuella.setBackground(Color.decode(util.colorFondo)
        );
        panelHuella.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Huella", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panelHuella.setLayout(new java.awt.BorderLayout());

        txtMsg.setBackground(Color.decode(util.colorFondo)
        );
        txtMsg.setColumns(20);
        txtMsg.setRows(5);
        jScrollPane2.setViewportView(txtMsg);

        panelHuella.add(jScrollPane2, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(Color.decode(util.colorFondo)
        );
        jPanel6.setLayout(new java.awt.GridBagLayout());

        lblMsg.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblMsg.setText("Favor de Colocar Dedo...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 3, 0);
        jPanel6.add(lblMsg, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Identificador: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 10, 10);
        jPanel6.add(jLabel3, gridBagConstraints);

        lblCliente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCliente.setText("Esperando...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(lblCliente, gridBagConstraints);

        rbtnIzquierda.setBackground(Color.decode(util.colorFondo)
        );
        rbtnIzquierda.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rbtnIzquierda.setText("Mano Izquierda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel6.add(rbtnIzquierda, gridBagConstraints);

        rbtnDerecha.setBackground(Color.decode(util.colorFondo)
        );
        rbtnDerecha.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rbtnDerecha.setText("Mano Derecha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel6.add(rbtnDerecha, gridBagConstraints);

        cmbDedo.setBackground(Color.decode(util.colorFondo)
        );
        cmbDedo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cmbDedo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulgar", "Indice", "Medio", "Anular", "Meñique" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        jPanel6.add(cmbDedo, gridBagConstraints);

        jPanel4.add(jPanel6, java.awt.BorderLayout.NORTH);

        lblImagen.setBackground(Color.decode(util.colorFondo)
        );
        jPanel4.add(lblImagen, java.awt.BorderLayout.CENTER);

        panelHuella.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelHuella, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        if(rbtnIzquierda.isSelected()){
            identificadorHuella=cmbDedo.getSelectedItem()+" izquierdo";
        }else{
            identificadorHuella=cmbDedo.getSelectedItem()+" derecho";
        }
        
        
        if(util.verificarString(identificadorHuella) && huella.banderaGuardado){
            int conf=JOptionPane.showConfirmDialog(this,"¿Desea huella para cliente: "+nombreCliente+"?");
        if(conf==0){
            if(huella.guardarHuella(idCliente,identificadorHuella.toUpperCase())){
            limpiarCampos();
            doClose(RET_OK);
            }else{
                
            }
        }else{
            
        }
        }else{
            jPanel6.setBackground(Color.decode(util.colorMal));
            JOptionPane.showMessageDialog(rootPane,"Verifique el campo de Identificador y que el contorno este en verde");
        }
        
        
        
        
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubHuella dialog = new SubHuella();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupMano;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cmbDedo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelHuella;
    private javax.swing.JRadioButton rbtnDerecha;
    private javax.swing.JRadioButton rbtnIzquierda;
    private javax.swing.JTextArea txtMsg;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
    
   
   public void iniciarHuella(Huella huella){
         System.out.print("Iniciando Huella en subhuella");
         
        this.huella=huella;
        this.huella.reclutador.clear();
        this.huella.stop();
        this.huella.setLabel(lblImagen,lblMsg,txtMsg,panelHuella);
        this.huella.start();
        this.huella.estadoHuellas();
        
    }
    public void limpiarCampos(){
        
        huella.reclutador.clear();
        huella.stop();
        huella.start();
        huella.estadoHuellas();
        huella.setLabel(lblImagen,lblMsg,txtMsg,panelHuella);
        panelHuella.setBackground(Color.white);
        lblImagen.setIcon(null);
        identificadorHuella="";
        
    }
    
    public boolean verificador(){
        boolean dev;
        Date hoy=new Date();
                        if(huella.banderaGuardado){
                            dev=true;
                            if(identificadorHuella.length()>0){
                                dev=true;
                            }else{
                                JOptionPane.showMessageDialog(this, "Verifique el campo para identificar la huella", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
                            dev=false;
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "Verifique el proceso de huella", "Huella no detectada", JOptionPane.WARNING_MESSAGE);
                            dev=false;
                        }
                    
    return dev;   
    }
    
    public void datosRecibidos(int id,String nombre){
        this.idCliente=id;
        this.nombreCliente=nombre;
        
        lblCliente.setText(nombreCliente);
    }
}
