/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isai.gym.paneles;

import com.isai.gym.clases.panelCarga;
import java.awt.BorderLayout;

/**
 *
 * @author isai_
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        cargarPanel();
    }
    
    
    
     public void cargarPanel(){
    panelCarga panel=new panelCarga();
    panel.setImagen("/GymImg/icono.jpeg");
    panel.updateUI();
    panelFondo.add(panel,BorderLayout.CENTER);
    panelFondo.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelFondo.setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");
        panelFondo.add(jButton1, java.awt.BorderLayout.CENTER);

        add(panelFondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
