/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isai.gym.paneles;

import com.isai.gym.clases.OperacionesDB;
import com.isai.gym.clases.Utilerias;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author isai_
 */
public class Paquete extends javax.swing.JPanel {

    Utilerias util= new Utilerias();
    OperacionesDB operDB= new OperacionesDB();
    /**
     * Creates new form Paquete
     */
    public Paquete() {
        initComponents();
        util.llenarTabla(tbPrincipalPaquetes, "paquetes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPrincipalPaquetes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbUnidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        panelMsg = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(Color.decode(util.colorFondo)
        );
        jPanel1.setPreferredSize(new java.awt.Dimension(688, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBackground(Color.decode(util.colorFondo));

        tbPrincipalPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPrincipalPaquetes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(Color.decode(util.colorFondo)
        );
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de paquetes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(Color.decode(util.colorFondo)
        );
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Nombre de paquete:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        txtNombre.setColumns(10);
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(txtNombre, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Unidad de periodo: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jcbUnidad.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jcbUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dias", "Meses" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(jcbUnidad, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Duracion de paquete: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtDuracion.setColumns(10);
        txtDuracion.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(txtDuracion, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_32/ic_disquete.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel3.add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_32/ic_cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel3.add(jButton2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Costo: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        txtCosto.setColumns(10);
        txtCosto.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(txtCosto, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.EAST);

        panelMsg.setPreferredSize(new java.awt.Dimension(688, 10));

        javax.swing.GroupLayout panelMsgLayout = new javax.swing.GroupLayout(panelMsg);
        panelMsg.setLayout(panelMsgLayout);
        panelMsgLayout.setHorizontalGroup(
            panelMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        panelMsgLayout.setVerticalGroup(
            panelMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(panelMsg, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        
        int conf=JOptionPane.showConfirmDialog(this,"¿Desea guardar el paquete: "+txtNombre.getText()+"?");
        if(conf==0){
         guardar();   
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    public void limpiarCampos(){
        txtNombre.setText("");
        txtDuracion.setText("");
        txtCosto.setText("");
        jcbUnidad.setSelectedIndex(0);
    }
    
    public void guardar(){
        if(util.verificarDouble("Costo",txtCosto.getText()) && util.verificarInt(txtDuracion.getText())){
            String[][]datos={{"nombre",txtNombre.getText()},
                         {"unidadMedida",jcbUnidad.getSelectedItem().toString()},
                         {"cantidad",txtDuracion.getText()},
                         {"estado","ACTIVO"},
                         {"costo",txtCosto.getText()}};
            
            String[][]verificador=util.verificarVariosString(datos);
            if(verificador[0][0].equals("CORRECTO")){
                if(operDB.guardarRegresandoId(datos,"paquetes")>0){
                    panelMsg.setBackground(Color.decode(util.colorBien));
                    limpiarCampos();
                    util.llenarTabla(tbPrincipalPaquetes, "paquetes");
                }else{
                panelMsg.setBackground(Color.decode(util.colorMal));    
                }
                    
                
            }else{
                panelMsg.setBackground(Color.decode(util.colorMal));    
                JOptionPane.showMessageDialog(this,"Verifique el campo: "+verificador[0][1]);
            }
        }else{
            panelMsg.setBackground(Color.decode(util.colorMal));    
            JOptionPane.showMessageDialog(this,"Verifique el campo de costos ");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbUnidad;
    private javax.swing.JPanel panelMsg;
    private javax.swing.JTable tbPrincipalPaquetes;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
