/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isai.gym.paneles;

import com.isai.gym.clases.Huella;
import com.isai.gym.clases.panelCarga;
import java.awt.BorderLayout;
import java.awt.Image;

/**
 *
 * @author isai_
 */
public class Validador extends javax.swing.JPanel {
    public Huella huella;
    

    /**
     * Creates new form Validador
     */
    public Validador() {
        initComponents();
        cargarPanel();
        lblNombre.setEditable(false);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JTextArea();
        panelEstado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTerminacion = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        panelInvi = new javax.swing.JPanel();
        lblInvi1 = new javax.swing.JLabel();
        lblInvi2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaInvi1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblNombre.setEditable(false);
        lblNombre.setColumns(20);
        lblNombre.setFont(new java.awt.Font("Dialog", 1, 80)); // NOI18N
        lblNombre.setRows(2);
        lblNombre.setText("\n");
        lblNombre.setBorder(null);
        lblNombre.setOpaque(false);
        jPanel1.add(lblNombre, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelEstado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        panelEstado.setOpaque(false);
        panelEstado.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Terminacion de paquete: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelEstado.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Estatus: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelEstado.add(jLabel2, gridBagConstraints);

        lblTerminacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTerminacion.setText("...");
        panelEstado.add(lblTerminacion, new java.awt.GridBagConstraints());

        lblDias.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDias.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelEstado.add(lblDias, gridBagConstraints);

        lblContador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContador.setText("Contador de visitas: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        panelEstado.add(lblContador, gridBagConstraints);

        add(panelEstado, java.awt.BorderLayout.PAGE_END);

        container.setOpaque(false);
        container.setLayout(new java.awt.BorderLayout());

        panelInvi.setOpaque(false);

        lblInvi1.setText("lblInvi1");

        lblInvi2.setText("jLabel7");

        jScrollPane1.setOpaque(false);

        txtAreaInvi1.setColumns(20);
        txtAreaInvi1.setRows(5);
        jScrollPane1.setViewportView(txtAreaInvi1);

        javax.swing.GroupLayout panelInviLayout = new javax.swing.GroupLayout(panelInvi);
        panelInvi.setLayout(panelInviLayout);
        panelInviLayout.setHorizontalGroup(
            panelInviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInviLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInviLayout.createSequentialGroup()
                        .addGroup(panelInviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInvi2)
                            .addComponent(lblInvi1))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInviLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelInviLayout.setVerticalGroup(
            panelInviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInviLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblInvi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInvi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.add(panelInvi, java.awt.BorderLayout.LINE_END);

        add(container, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblInvi1;
    private javax.swing.JLabel lblInvi2;
    private javax.swing.JTextArea lblNombre;
    private javax.swing.JLabel lblTerminacion;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelInvi;
    private javax.swing.JTextArea txtAreaInvi1;
    // End of variables declaration//GEN-END:variables

    public void cargarPanel(){
    panelCarga panel=new panelCarga();
    panel.setImagen("/GymImg/banner.jpeg");
    panel.updateUI();
    container.add(panel,BorderLayout.CENTER);
    container.updateUI();
    }

    
    public void valorHuella(Huella huella){
        this.huella=huella;
        iniciarSensor();
    }
    public void iniciarSensor(){
        
        huella.reclutador.clear();
        huella.stop();
        huella.start();
        huella.setLabel(lblInvi1, lblInvi2, txtAreaInvi1, panelInvi);
        huella.setBandera(true, lblNombre,lblTerminacion,lblDias,this,lblContador);
        panelInvi.setVisible(false);
    }
    
    public void terminarSensor(){
        
    }

    
}
