/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isai.gym;

import com.isai.gym.clases.Huella;
import com.isai.gym.clases.Utilerias;
import com.isai.gym.paneles.Clientes;
import com.isai.gym.paneles.Cobros;
import com.isai.gym.paneles.Empleados;
import com.isai.gym.paneles.Inicio;
import com.isai.gym.paneles.Paquete;
import com.isai.gym.paneles.Validador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author isai_
 */
public class Principal extends javax.swing.JFrame {

    String usoHuella="";
    Huella huella= new Huella();
    Utilerias util=new Utilerias();
    int idUsuarioActivo;
    String nombreUsuarioActivo;
    
    /**
     * Creates new form Principal
     */
    public Principal(int idUsuario) {
        idUsuarioActivo=idUsuario;
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Imposible modificar el tema visual","Lookandfelel invaildo.",JOptionPane.ERROR_MESSAGE);
        }
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/GymImg/icono.jpeg")));
        
        initComponents();
        this.setExtendedState(Principal.MAXIMIZED_BOTH);
        panelMenu.setVisible(false);
        huella.inciar();
        huella.start();
        btnInicio.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JButton();
        lblActivo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnPlanes = new javax.swing.JButton();
        btnCobro = new javax.swing.JButton();
        btnVerificador = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(Color.decode(util.colorDark)
        );
        jPanel1.setLayout(new java.awt.BorderLayout());

        Menu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Menu.setIcon(new ImageIcon(getClass().getResource("/ic_32/ic_menu.png")));
        Menu.setText("Menu");
        Menu.setBorderPainted(false);
        Menu.setContentAreaFilled(false);
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, java.awt.BorderLayout.LINE_START);

        lblActivo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblActivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActivo.setText("jLabel1");
        lblActivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblActivo, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_32/ic_confi.png"))); // NOI18N
        jButton1.setText("Configuraciones");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelMenu.setBackground(Color.decode(util.colorPrimario)
        );
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));

        btnInicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_64/ic_home_bn.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnInicioFocusGained(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelMenu.add(btnInicio);

        btnClientes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_64/ic_clientes_bn.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnClientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnClientesFocusLost(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelMenu.add(btnClientes);

        btnPlanes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPlanes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_64/ic_plan_bn.png"))); // NOI18N
        btnPlanes.setText("Planes");
        btnPlanes.setBorderPainted(false);
        btnPlanes.setContentAreaFilled(false);
        btnPlanes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnPlanesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnPlanesFocusLost(evt);
            }
        });
        btnPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanesActionPerformed(evt);
            }
        });
        panelMenu.add(btnPlanes);

        btnCobro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_64/ic_cobro_bn.png"))); // NOI18N
        btnCobro.setText("Cobro");
        btnCobro.setBorderPainted(false);
        btnCobro.setContentAreaFilled(false);
        btnCobro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCobroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCobroFocusLost(evt);
            }
        });
        btnCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobroActionPerformed(evt);
            }
        });
        panelMenu.add(btnCobro);

        btnVerificador.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVerificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_64/ic_identificar_bn.png"))); // NOI18N
        btnVerificador.setText("Verificador");
        btnVerificador.setBorderPainted(false);
        btnVerificador.setContentAreaFilled(false);
        btnVerificador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnVerificadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnVerificadorFocusLost(evt);
            }
        });
        btnVerificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificadorActionPerformed(evt);
            }
        });
        panelMenu.add(btnVerificador);

        btnEmpleados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_64/ic_empleado_bn.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        panelMenu.add(btnEmpleados);

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        container.setLayout(new java.awt.BorderLayout());
        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        
        if(panelMenu.isVisible()){
            panelMenu.setVisible(false);
        }else{
            panelMenu.setVisible(true);
        }
    }//GEN-LAST:event_MenuActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        menuActivo("Inicio");
        Inicio pI=new Inicio();
        
        container.add(pI,BorderLayout.CENTER);
        
        container.updateUI();
        panelMenu.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnInicioFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnInicioFocusGained

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        menuActivo("Clientes");

        Clientes pc=new Clientes();
        //pc.valorHuella(huella);
        container.add(pc,BorderLayout.CENTER);
        pc.valorHuella(huella);
        container.updateUI();
        panelMenu.setVisible(false);
        
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClientesFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnClientesFocusGained

    private void btnClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnClientesFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnClientesFocusLost

    private void btnPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanesActionPerformed
        // TODO add your handling code here:
        menuActivo("Planes");
        container.removeAll();
        Paquete pp=new Paquete();
        container.add(pp,BorderLayout.CENTER);
        container.updateUI();
        panelMenu.setVisible(false);
    }//GEN-LAST:event_btnPlanesActionPerformed

    private void btnPlanesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPlanesFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPlanesFocusGained

    private void btnPlanesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPlanesFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPlanesFocusLost

    private void btnCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobroActionPerformed
        // TODO add your handling code here:
        menuActivo("Cobro");
        container.removeAll();
        Cobros pco=new Cobros();
        container.add(pco,BorderLayout.CENTER);
        pco.valorHuella(huella);
        pco.iniciarSensor();
        container.updateUI();
        panelMenu.setVisible(false);
        
    }//GEN-LAST:event_btnCobroActionPerformed

    private void btnVerificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificadorActionPerformed
        // TODO add your handling code here:
        menuActivo("Verificador");
        Validador pv=new Validador();
        container.removeAll();    
        container.add(pv,BorderLayout.CENTER);
        pv.valorHuella(huella);
        container.updateUI();
        panelMenu.setVisible(false);
        pv.iniciarSensor();
        
        
        
        
    }//GEN-LAST:event_btnVerificadorActionPerformed

    private void btnCobroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCobroFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCobroFocusGained

    private void btnCobroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCobroFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCobroFocusLost

    private void btnVerificadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnVerificadorFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnVerificadorFocusGained

    private void btnVerificadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnVerificadorFocusLost
        // TODO add your handling code here: 
    }//GEN-LAST:event_btnVerificadorFocusLost

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
         menuActivo("Empleados");
        
        Empleados pe=new Empleados();
        container.removeAll();    
        container.add(pe,BorderLayout.CENTER);
        
        container.updateUI();
        panelMenu.setVisible(false);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(0).setVisible(true);
                
            }
        });
    }
    
    public void menuActivo(String menu){
        lblActivo.setText(menu);
        switch(menu){
            case "Inicio":
                btnInicio.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_home.png")));
                btnClientes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_clientes_bn.png")));
                btnPlanes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_plan_bn.png")));
                btnCobro.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cobro_bn.png")));
                btnVerificador.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_identificar_bn.png")));
                btnEmpleados.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_empleado_bn.png")));
                break;
            case "Clientes":
                btnInicio.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_home_bn.png")));
                btnClientes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cliente.png")));
                btnPlanes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_plan_bn.png")));
                btnCobro.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cobro_bn.png")));
                btnVerificador.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_identificar_bn.png")));
                btnEmpleados.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_empleado_bn.png")));
                break;
            case "Planes":
                btnInicio.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_home_bn.png")));
                btnClientes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_clientes_bn.png")));
                btnPlanes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_plan.png")));
                btnCobro.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cobro_bn.png")));
                btnVerificador.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_identificar_bn.png")));
                btnEmpleados.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_empleado_bn.png")));
                break;
            case "Cobro":
                btnInicio.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_home_bn.png")));
                btnClientes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_clientes_bn.png")));
                btnPlanes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_plan_bn.png")));
                btnCobro.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cobro.png")));
                btnVerificador.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_identificar_bn.png")));
                btnEmpleados.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_empleado_bn.png")));
                break;
            case "Verificador":
                btnInicio.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_home_bn.png")));
                btnClientes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_clientes_bn.png")));
                btnPlanes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_plan_bn.png")));
                btnCobro.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cobro_bn.png")));
                btnVerificador.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_identificar.png")));
                btnEmpleados.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_empleado_bn.png")));
                break;
            case "Empleados":
                btnInicio.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_home_bn.png")));
                btnClientes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_clientes_bn.png")));
                btnPlanes.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_plan_bn.png")));
                btnCobro.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_cobro_bn.png")));
                btnVerificador.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_identificar_bn.png")));
                btnEmpleados.setIcon(new ImageIcon(getClass().getResource("/ic_64/ic_empleado.png")));
                break;
        }
    }
    
    public void permisos(String [] datos){
        
            if(datos[0].equals("1")){
                btnClientes.setEnabled(true);
            }else{
                btnClientes.setEnabled(false);
            }
            if(datos[1].equals("1")){
                btnPlanes.setEnabled(true);
            }else{
                btnPlanes.setEnabled(false);
            }
            if(datos[2].equals("1")){
                btnCobro.setEnabled(true);
            }else{
                btnCobro.setEnabled(false);
            }
            if(datos[3].equals("1")){
                btnVerificador.setEnabled(true);
            }else{
                btnVerificador.setEnabled(false);
            }
            if(datos[4].equals("1")){
                btnEmpleados.setEnabled(true);
            }else{
                btnEmpleados.setEnabled(false);
            }
                    
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCobro;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPlanes;
    private javax.swing.JButton btnVerificador;
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActivo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
